fs.delete("startup.lua")
shell.execute("wget", "https://raw.githubusercontent.com/ShoddyShoe/CC-Tweaked-Scripts/main/Quarry/Minion/startup.lua")
rednet.open("left")
rednet.send(tonumber(...), "Updated!")
os.shutdown()
